name: sync mirror bucket
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: 🚀️ sync mirror in codeberg
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/magicedy/scoop-bucket-m.git'
          REMOTE_NAME: codeberg
          GIT_USERNAME: magicedy
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}

      - name: 🚀️ sync mirror in gitea
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitea.com/magicedy/scoop-bucket-m.git'
          REMOTE_NAME: gitea
          GIT_USERNAME: magicedy
          GIT_PASSWORD: ${{ secrets.GITEA_TOKEN }}
